package claude

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/DanBradbury/firekeeper/internal/session"
	"github.com/DanBradbury/firekeeper/internal/transcript"
	"github.com/DanBradbury/firekeeper/internal/transcript/transcripttest"
)

const (
	fixtureID   = "0199c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"
	fixturePath = "testdata/" + fixtureID + ".jsonl"
	malformed   = "testdata/malformed.jsonl"
)

type want struct {
	role   transcript.Role
	text   string
	tool   string
	model  string
	tokens transcript.Tokens
}

func TestReadTranscript(t *testing.T) {
	events, end, err := (&Source{}).Read(fixturePath, 0)
	if err != nil {
		t.Fatal(err)
	}
	info, _ := os.Stat(fixturePath)
	if end != info.Size() {
		t.Fatalf("end offset = %d, want file size %d", end, info.Size())
	}
	const model = "claude-test"
	expected := []want{
		0: {role: transcript.RoleMeta},
		1: {role: transcript.RoleSystem, text: "Caveat: generated by a local command."},
		2: {role: transcript.RoleUser, text: "List the files."},
		3: {role: transcript.RoleMeta},
		// The three blocks of msg_1 repeat its usage; only the first counts.
		4:  {role: transcript.RoleMeta, text: "Planning.", model: model, tokens: transcript.Tokens{Input: 3, Output: 40, Cache: 1200}},
		5:  {role: transcript.RoleAssistant, text: "Listing files.", model: model},
		6:  {role: transcript.RoleToolCall, text: `{"command":"ls"}`, tool: "Bash", model: model},
		7:  {role: transcript.RoleToolResult, text: "README.md", tool: "Bash"},
		8:  {role: transcript.RoleToolCall, text: `{"question":"Continue?"}`, tool: "AskUserQuestion", model: model, tokens: transcript.Tokens{Input: 5, Output: 20, Cache: 1200}},
		9:  {role: transcript.RoleToolResult, text: "yes", tool: "AskUserQuestion"},
		10: {role: transcript.RoleAssistant, text: "There is one file: README.md.", model: model, tokens: transcript.Tokens{Input: 2, Output: 10, Cache: 1300}},
		11: {role: transcript.RoleSystem},
		12: {role: transcript.RoleSystem, text: "<local-command-stdout>ok</local-command-stdout>"},
		13: {role: transcript.RoleAssistant, text: "API Error: overloaded"},
		// Sidechain records stay meta but keep their content.
		14: {role: transcript.RoleMeta, text: "Search for TODOs."},
		15: {role: transcript.RoleMeta, text: `{"pattern":"TODO"}`, tool: "Grep", model: model, tokens: transcript.Tokens{Input: 1, Output: 2, Cache: 3}},
		16: {role: transcript.RoleMeta},
		17: {role: transcript.RoleMeta},
	}
	checkEvents(t, events, expected, fixtureID)
	for _, e := range events {
		if hasTimestamp := e.Seq >= 1 && e.Seq <= 15; hasTimestamp != (e.TS != nil) {
			t.Errorf("seq %d: timestamp present = %v", e.Seq, e.TS != nil)
		}
	}
	for _, seq := range []int{14, 15} {
		var raw struct {
			IsSidechain bool `json:"isSidechain"`
		}
		if json.Unmarshal(events[seq].Raw, &raw) != nil || !raw.IsSidechain {
			t.Errorf("seq %d: raw should keep the isSidechain tag", seq)
		}
	}
}

func TestReadMalformed(t *testing.T) {
	events, _, err := (&Source{}).Read(malformed, 0)
	if err != nil {
		t.Fatal(err)
	}
	expected := []want{
		0:  {role: transcript.RoleMeta},
		1:  {role: transcript.RoleUser, text: "hello"},
		2:  {role: transcript.RoleMeta},
		3:  {role: transcript.RoleMeta},
		4:  {role: transcript.RoleAssistant, text: "plain string"},
		5:  {role: transcript.RoleToolResult},
		6:  {role: transcript.RoleMeta},
		7:  {role: transcript.RoleMeta},
		8:  {role: transcript.RoleMeta},
		9:  {role: transcript.RoleSystem},
		10: {role: transcript.RoleMeta},
		11: {role: transcript.RoleMeta},
	}
	// The file name carries no session id, so the records supply it.
	checkEvents(t, events, expected, "0199c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6e")
	if events[1].TS != nil {
		t.Error("seq 1: unparseable timestamp should be null")
	}
	for _, seq := range []int{2, 11} {
		var quoted string
		if json.Unmarshal(events[seq].Raw, &quoted) != nil {
			t.Errorf("seq %d: invalid JSON line should be kept as a JSON string in raw", seq)
		}
	}
}

func checkEvents(t *testing.T, events []transcript.Event, expected []want, sessionID string) {
	t.Helper()
	if len(events) != len(expected) {
		t.Fatalf("got %d events, want %d", len(events), len(expected))
	}
	for i, e := range events {
		w := expected[i]
		if err := e.Validate(); err != nil {
			t.Errorf("seq %d: %v", i, err)
		}
		if e.Seq != int64(i) || e.Role != w.role || e.Text != w.text || deref(e.ToolName) != w.tool ||
			deref(e.Model) != w.model || e.Tokens != w.tokens {
			t.Errorf("seq %d: got seq %d role %s tool %q model %q tokens %+v text len %d; want role %s tool %q model %q tokens %+v text len %d",
				i, e.Seq, e.Role, deref(e.ToolName), deref(e.Model), e.Tokens, len(e.Text), w.role, w.tool, w.model, w.tokens, len(w.text))
		}
		if e.SessionID != sessionID || e.Provider != transcript.ProviderClaude {
			t.Errorf("seq %d: session %q provider %q", i, e.SessionID, e.Provider)
		}
	}
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func TestSeqStability(t *testing.T) {
	transcripttest.RunSeqStability(t, &Source{}, []transcripttest.SeqCase{
		{Name: "transcript", Path: fixturePath},
		{Name: "malformed", Path: malformed},
	})
}

// A split read must recover tool names and counted usage from before the
// offset; the stability helper compares neither tokens nor models.
func TestReadFromOffsetRestoresState(t *testing.T) {
	source := &Source{}
	whole, _, err := source.Read(fixturePath, 0)
	if err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(fixturePath)
	for _, split := range []int{5, 7, 9} {
		offset := 0
		for range split {
			offset += strings.IndexByte(string(data[offset:]), '\n') + 1
		}
		tail, _, err := source.Read(fixturePath, int64(offset))
		if err != nil {
			t.Fatal(err)
		}
		if len(tail) != len(whole)-split {
			t.Fatalf("split %d: got %d events, want %d", split, len(tail), len(whole)-split)
		}
		for i, e := range tail {
			w := whole[split+i]
			if e.Seq != w.Seq || e.Tokens != w.Tokens || deref(e.Model) != deref(w.Model) ||
				deref(e.ToolName) != deref(w.ToolName) || e.SessionID != w.SessionID {
				t.Errorf("split %d: seq %d differs between split and whole reads", split, w.Seq)
			}
		}
	}
}

func TestReadIncompleteTrailingLine(t *testing.T) {
	data, _ := os.ReadFile(fixturePath)
	lines := strings.SplitAfter(string(data), "\n")
	path := filepath.Join(t.TempDir(), filepath.Base(fixturePath))
	complete := lines[0] + lines[1]
	if err := os.WriteFile(path, []byte(complete+lines[2][:10]), 0o600); err != nil {
		t.Fatal(err)
	}
	events, offset, err := (&Source{}).Read(path, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != 2 || offset != int64(len(complete)) {
		t.Fatalf("got %d events at offset %d; want 2 at %d", len(events), offset, len(complete))
	}
	// The writer finishes the line; the next read picks it up as seq 2.
	if err := os.WriteFile(path, []byte(complete+lines[2]), 0o600); err != nil {
		t.Fatal(err)
	}
	events, _, err = (&Source{}).Read(path, offset)
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != 1 || events[0].Seq != 2 || events[0].Role != transcript.RoleUser {
		t.Fatalf("resumed read gave %d events", len(events))
	}
}

func TestReadBadOffsets(t *testing.T) {
	info, _ := os.Stat(fixturePath)
	for name, offset := range map[string]int64{
		"negative":      -1,
		"past end":      info.Size() + 1,
		"mid line":      5,
		"truncated end": info.Size() - 1,
	} {
		t.Run(name, func(t *testing.T) {
			if _, _, err := (&Source{}).Read(fixturePath, offset); err == nil {
				t.Fatal("expected error")
			}
		})
	}
	_, _, err := (&Source{}).Read(filepath.Join(t.TempDir(), "missing.jsonl"), 0)
	if err == nil || strings.Contains(err.Error(), string(filepath.Separator)) {
		t.Fatalf("missing file error = %v; want an error without a path", err)
	}
}

func TestToolOutputTruncated(t *testing.T) {
	big := strings.Repeat("é", maxToolText) // two bytes per rune
	line, _ := json.Marshal(map[string]any{
		"type":      "user",
		"timestamp": "2026-01-02T03:04:05.000Z",
		"message": map[string]any{"role": "user", "content": []any{
			map[string]any{"type": "tool_result", "tool_use_id": "t", "content": big},
		}},
	})
	path := filepath.Join(t.TempDir(), fixtureID+".jsonl")
	if err := os.WriteFile(path, append(line, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
	events, _, err := (&Source{}).Read(path, 0)
	if err != nil {
		t.Fatal(err)
	}
	text := events[0].Text
	kept, marker, ok := strings.Cut(text, "\n[truncated ")
	if !ok || len(kept) != maxToolText || marker != "65536 bytes]" {
		t.Fatalf("kept %d bytes, marker %q", len(kept), marker)
	}
	if !strings.Contains(string(events[0].Raw), big) {
		t.Fatal("raw should keep the full output")
	}
}

func TestLocate(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "projects", "-work-demo")
	other := filepath.Join(dir, "projects", "-work-other")
	for _, d := range []string{project, other, filepath.Join(project, fixtureID, "subagents")} {
		if err := os.MkdirAll(d, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	live := filepath.Join(project, fixtureID+".jsonl")
	elsewhere := filepath.Join(other, "0199c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6f.jsonl")
	for _, path := range []string{live, elsewhere, filepath.Join(project, fixtureID, "subagents", "agent-1.jsonl")} {
		if err := os.WriteFile(path, nil, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	source := &Source{ConfigDir: dir}
	tests := []struct {
		name string
		meta session.Meta
		want []string
	}{
		{"path from discovery", session.Meta{Provider: "claude", ID: fixtureID, RolloutPath: live}, []string{live}},
		{"search by id", session.Meta{Provider: "claude", ID: fixtureID}, []string{live}},
		{"any project directory", session.Meta{ID: "0199c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6f"}, []string{elsewhere}},
		{"stale path falls back to search", session.Meta{ID: fixtureID, RolloutPath: filepath.Join(dir, "gone", fixtureID+".jsonl")}, []string{live}},
		{"path for another id is ignored", session.Meta{ID: fixtureID, RolloutPath: elsewhere}, []string{live}},
		{"no transcript yet", session.Meta{ID: "0199c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c60"}, nil},
		{"no id", session.Meta{Provider: "claude"}, nil},
		{"other provider", session.Meta{Provider: "codex", ID: fixtureID}, nil},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := source.Locate(tt.meta)
			if err != nil {
				t.Fatal(err)
			}
			if strings.Join(got, ",") != strings.Join(tt.want, ",") {
				t.Fatalf("Locate = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestLocateHonorsClaudeConfigDir(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "projects", "-work-demo")
	if err := os.MkdirAll(project, 0o700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(project, fixtureID+".jsonl")
	if err := os.WriteFile(path, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CLAUDE_CONFIG_DIR", dir)
	got, err := (&Source{Home: t.TempDir()}).Locate(session.Meta{ID: fixtureID})
	if err != nil || len(got) != 1 || got[0] != path {
		t.Fatalf("Locate = %v, %v", got, err)
	}
}

func TestRegistered(t *testing.T) {
	if _, ok := transcript.For(transcript.ProviderClaude); !ok {
		t.Fatal("claude source not registered")
	}
}
